CondeNast/launch-vehicle-fbm

- config/custom-environment-variables.json
- example.env
- src/app.js
- src/conversationLogger.js
- test/app.spec.js
- test/conversationLogger.spec.js
`ConversationLoggger` is a viable, stand-alone, (open source)? module and this does some cleanup that will help maintainability and open to the door to it being separated from the SDK should we decide that in the future.
No additional documentation added. There is no standalone `README` for this and these changes are all internal to the SDK so nothing that is currently documented in the `README` changes. The minimal changes to the tests should back this up.
`npm i`
`npm t`
Testing against a skeleton bot:
* link this library via `npm link`
* use [this gist] as a test bot
* run the bot!
[this gist]: https://gist.github.com/stripethree/3fa81ea549957502bd0c1b7b85ae5abf
While this PR touts decoupling this as a standalone module, the configuration namespacing is still tied to the SDK. Thus, it …
> Conversion of conversation logger to a standalone module

- README.md
In the Node ecosystem, there are a lot of packages that all do kinda the same thing. I appreciate when a READMEs document similar packages and what the differences are from an expert's point of view. It turns out that for Messenger, it would be hard to maintain this in the README, so this PR adds a link to a new wiki page where that information can be kept.
Closes #13 
The wiki page seems decent, nothing wrong with starting small.
View the rendered version of the README in Github. The link should work and go to https://github.com/CondeNast/launch-vehicle-fbm/wiki/Prior-art
Time progresses and information gets out of date, eventually becoming unhelpful.
none
non
N/A
> Doc just enough to link back to a Prior Art wiki page

- src/app.js
- src/conversationLogger.js
In the conversation logger refactor #23 , a global options became an instance attribute `this.options`. Unfortunately, because Winston calls `this.slackFormatter` and not the `ConversationLogger` instance, `this.options` changed unexpectedly to reference the Winston logger and was `undefined` when we meant for it to reference `ConversationLogger.options`.
Some additional Flow type docs added while trying to debug this.
1. Run the bot in a dev environment (`npm link`)
2. You don't need to enable Slack config, but it's nice
3. Messaging the bot should not result in a `TypeError: Cannot read property 'slackChannel' of undefined`
* I may have missed another `this` for something else, but we can tackle that when it shows
* none
none
Increases with Flow …
> Fix how this.options was referencing wrong object in conversationLogger

- README.md
- src/index.js
- src/responses.js
- test/main.spec.js
- test/responses.spec.js
Currently, if users want to use the response object factories, they have to reach into the source (which also currently requires knowledge of the source tree). This adds documentation for how to use them and also makes them easier to access.
closes #21 
Some major rework of the README
Just unit tests (`main.spec.js`). You can npm link this in to a side project but that's going above what you should need to do to test this.
* none
* I noted that quick replies are still a WIP, so we'll have to revisit that one day
* If the user assumes they can tree shake `require('launch-vehicle-fbm/responses/Text')`, they'll be sad. But this isn't documented so that's ok.
new code is covered
> Make response factories easier to access

- README.md
- package.json
- src/app.js
- src/conversationLogger.js
To enable two bots one page for a new conversation logger, you need the ability to make a bot that can listen to echo messages. Otherwise, the observer bot can only observe humans.
After talking through #34, the double opt-in seemed excessive. This PR solves the same problem, but with only one opt-in, and so less code.
closes #29
README now talks about echo messages
1.  Edit the webhook for a bot to get echos too
2. view the log to see more events come in
* none. If a user gets echos and it triggers things, then the app should either stop listening to echos and/or they should check the echo themselves.
* none
none
stays the same. code was deleted, and that code wasn't really covered, so... maybe this increases coverage?
> Kill killswitch for events that come in via message_echoes

- src/app.js
This is a copy paste of a fix that wasn't copy pasted into the initial SDK. Cacheman has a default TTL of [60 seconds](https://github.com/cayasso/cacheman/blob/6149f436268cedbec54633c81481ae7035411873/lib/index.js#L99-L104) but [it's not documented](https://github.com/cayasso/cacheman/issues/37). This meant if you took a break in the middle of a quiz, it would freeze on you.
This explicitly sets the TTL, which increases documentation
Can't test within the SDK, but this is a copy paste
* Uptime
* Security
* Performance degradation
* Data loss
If applicable, include a technical debt note. Do a quick estimate of if this pull request increases or decreases technical debt. Leave a message to future developers about why increased technical debt is worth it, or brag about how you figured out how …
> Fix session timeouts

- README.md
- package.json
- src/responses.js
- test/responses.spec.js
The text translation helps us write smaller code, but if you need to do special formatting, like "Fetched %d out of %d", you currently have to write out the whole string yourself, which can lead to very long lines, which is one of the major reasons why the `Text` translation layer exists in the first place. This adds [`util.format`](https://nodejs.org/docs/latest/api/util.html#util_util_format_format_args) to `Text` so it knows how to do this kind of formatting in a way that's consistent with `console` and printf and gettext.
closes #22
New functionality is in the README and there are test cases for some edge cases where I wondered what would happen.
Since this is in the SDK, there's only unit tests unless you `npm link` in and do a manual test. I …
> Add printf-like formatting to Text response helper

- README.md
- src/app.js
This is a documentation update for some missing information. I tried looking for it in the past assuming it was there. Since `session.profile` is provided by the SDK, it's worth writing something even if it does just point to Facebook's docs.
closes #32 
this is it
1. view the [rendered readme](https://github.com/CondeNast/launch-vehicle-fbm/blob/d9fc92ec34948b257bb9699613ddc2411b188c7f/README.md)
2. clicking on a hotlinked "a session object" should take you to the session docs
* increases docs tech debt, but I managed to cop out by trying to get people to go to the official docs for more info
none
N/A
N/A
> Document session.profile

- src/app.js
- test/app.spec.js
The long term goal is to have one bot service multiple pages. To do that, we need to associate conversations with a page. Lucky for us, we have the `session` storage around. This PR:
* adds an internal `_pageId` to the session object
* adds some Flow type documentation I wish existed to document some function signatures
* fixes some leaky tests
This is a precursor to #30
The session object doesn't require a README update because it's internal. There are new Flow docs. Functionality and the API does not change.
Just unit tests. I also ran this `npm link`ed to another bot and it ran as usual.
* minor: increases the payload and responsibility of the session object
* #30 Sending based on page id
* major rework of page id/page access token config
none
new code is covered, 
increases with flow …
> Store the page id for conversations in the session

- README.md
- package.json
- src/app.js
- src/index.js
- test/app.spec.js
We need to expand the session cache to live outside the current memory cache. This PR adjusts the `Messenger` constructor to take in a new optional option: `cache`. If supplied, `Messenger` will use this new cache instead of the default.
Some other changes:
* refactor to reduce Flow type warnings
* refactor to remove `__internals__` hack
* remove unnecessary namespacing that the redis cache backend handles already
closes #47 
closes #41 (makes this obsolete)
closes #45 (documentation)
The readme documents the basics of how to supply your own cache. If the cacheman-redis library were more elegant, I'd include an example but it's very awkward to use so I opted to punt on including an example to avoid including a confusing example.
1. `npm i`
2. `npm t` …
> Add ability to bring your own cache storage

- README.md
- package.json
- src/app.js
- test/app.spec.js
Currently, the SDK assumes that the bot will only be deployed on one page. But Facebook lets you  associate a bot with multiple pages. This PR adds the plumbing necessary so calls that depend on the page now take `pageId` as an argument. The SDK constructor has a new option for page ids because it needs to know how to turn a page id into an access token. For now, the new `pageId` is optional as long as the user still has the existing page id and page access token config set.
* getPublicProfile can work for multiple pages
* send can work for multiple pages
* configuration is split better between config needed bot config for listening (app) and config for responding (page).
Closes #30 
* It turns out a lot of the API wasn't really documented, so this adds documentation using the current …
> Add plumbing for page specific operations

- README.md
- src/app.js
- test/app.spec.js
Following the discussion on #54, it was determined that there is value in adding events related to the application starting up. This PR adds `app.starting` and `app.started` to communicate status from the SDK to the application.
Yes, the `README` has been updated with information on the new events.
`npm i`
`npm t`
Optionally, start up a test bot that responds to these events. Some sample code to use:
```javascript
messenger.on('app.starting', ({port}) => {
console.log(`The launch vehicle boosters are firing on port ${port}; getting ready for launch...`);
});
messenger.on('app.started', ({port}) => {
console.log(`Lift off! The launch vehicle is now listening for requests on port ${port}`);
});
```
These events are informational and no adverse effects have been identified.
Decide if we want …
> Add 'app.starting' and 'app.started' events

- src/app.js
This implements a very old TODO. When starting the server, you get a logging statement when it's up to give you feedback on what port it's running on so you can test it out. This improves that feedback with a url. Based on a guessed host of `localhost`. We could probably dig in and find a more accurate host name, but if they're running in Docker, the hostname we grab won't work anyways. Users can now option-click on the url to test the webhook. It also logs the webhook url. If the user is setting up the Facebook app settings, they'll know what url to put.
It's one log line instead of two because I see this as one event. And I believe in 1 event == 1 log line.
N/A
1. `npm link` here
2. `npm link launch-vehicle-fbm` in an existing bot
3. When you start …
> Log the webhook to ease first time setup

- test/app.spec.js
- test/conversationLogger.spec.js
- test/main.spec.js
- test/responses.spec.js
Using `sandbox` rather than `sinon` simplifies the `afterEach` and is also common to our application practices at Condé Nast. Simplifying this small part of the testing setup and teardown process also likely encourages more tests!
Credit to @tswicegood for pointing this out [in a comment] on #56 
closes #57
[in a comment]: https://github.com/CondeNast/launch-vehicle-fbm/pull/56/files#r112085008
N/A - testing changes only and tests themselves aren't impacted, just the setup and teardown.
`npm i`
`npm t`
🎉 
None identified.
None identified.
Moving a few things from `before` to `beforeEach` could result in a small latency hit but nothing that should be terrible.
Nope!
> Sandbox the tests: move from `sinon.stub` to `sandbox`

- src/app.js
- test/app.spec.js
This PR limits calling `verifyRequestSignature` to `POST` routes with the`application/json` header to only the route defined by `messenger.options.webhook`. The `verifyRequestSignature` function performs a validation that is specific to Facebook Messenger and calling this on any `POST` with the `application/json` header was effectively blocking application developers from adding other routes to the Express server instance in `messenger`.
docs for the handler: http://expressjs.com/en/4x/api.html#app.METHOD
Closes #61 
No `README` updates as these changes ars all under the hood. Also, the argument can be made that this should have been the expected behavior instead of what is currently implemented.
`npm i`
`npm t`
Optionally, create and run a test bot that has an added `POST` route. …
> Limit `verifyRequestSignature` calls on `application/json` POSTs to the Messenger webhook route

- package-lock.json
- package.json
- src/app.js
- src/responses.js
- test/app.spec.js
- test/conversationLogger.spec.js
This adds Npm v5's `package-lock.json`. It also updates some dependencies. Eventually, someone else will be running Npm v5 and will generate this file too, so I'm committing it now for the future.
N/A
1. `npm i`
2. `npm t`
* As usually, some dep update may break something, but no major prod dep versions were upgraded.
* The `package-lock.json` throws off github line diff counts, so they no longer mean anything.
none
none
none, keeps the project up to date.
> Add npm@5 package-lock.json artifact

- README.md
- package-lock.json
- package.json
- src/app.js
- src/conversationLogger.js
While doing prep work for a feature, I decided to change the defaults to make them more realistic based on our usage of the SDK. By changing this value, users will get more value out of the bot using just the default configuration. We previously bumped it from 1 minute (the default for the base library) to 1 hour. But when users tested bots, they would often leave for over an hour and come back.
To get users to switch to a real cache end, there's a new line to go look in the wiki for a Redis example. There isn't a great example right now, but if they look at the multitenant example, they'll find Redis.
yep
1. npm i
2. npm t
* More memory usage, but just barely
* something breaking in a dependency
* make a more contrived Redis example in the wiki
none …
> Bump cache timeout from 1hr to 1day

- README.md
- package-lock.json
- package.json
- src/app.js
- test/app.spec.js
For most bots, users will want the ability to pause the bot just for a user so they can talk to them without the bot's automated responses filling the conversation. An example would be a customer service bot where the user signals they're ready to talk to a human. This adds a webhook that sets a cache key that will cause the bot to stop processing just for a user.
Follow Dashbot's guide: https://www.dashbot.io/sdk/pause
closes #67 
I added a new section to the README for the http endpoints available.
Just unit tests since this is the sdk.
1. `npm i`
2. `npm t`
* there's a new cache key, so that means you need another cache lookup, which increases the latency to the message
* none
none
new code is covered
> Add "pause" webhook to allow for live person takeovers

- README.md
- package-lock.json
- package.json
- src/responses.js
- test/responses.spec.js
We made a way to do Image + quick replies but not Text + quick replies. This adds that missing message type, it also deprecates the old `ImageQuickReply` helper in favor of plain `Text` and `Image` + `.quickReplies()` method. Adding quick replies isn't really a new message type, it's a modification of existing types. The syntax from the tests and README look like:
const text = new Text('Where are you?').quickReplies([{ content_type: 'location' }])
closes #60 
README is updated. I wonder if this should move to the wiki though, the README is getting heavy.
1. `npm i`
2. `npm t`
* none
tech debt increases slightly but can improve when `ImageQuickReply` is removed. There's also some potential for a DRY refactor
* release minor version bump
none
new code is …
> Add support for Text quick replies

- src/app.js
- test/app.spec.js
The bot tries to get a profile, but it's a convenience, not a requirement. If for some reason the profile can't be loaded, it should not be a show stopper. There are already cases where we can't get a profile (bot messing a bot) where we fallback to an empty object and log a warning.
This PR also implements a longstanding related TODO and fixes the fallback case for the greeting message.
No README updates necessary. Code comments and type defs are updated.
1. `npm t`
* none. If someone was relying on this obscure code blowing up, that should be fixed on their side
* none
none
increases, the profile fetching logic inside `routeEachMessage` wasn't covered before.
> Use fallback instead of exploding when failing to get a profile

- README.md
- package-lock.json
- package.json
- src/app.js
- test/app.spec.js
Messenger has "parametric messenger codes". When these visual codes are scanned, the bot is supposed to be able to respond. Facebook created a new `referral` event for this, even though it's the same thing as `postback` 🤷‍♂️ . This PR adds support for this new event, following the naming conventions for the other events.
https://developers.facebook.com/docs/messenger-platform/discovery/messenger-codes/
README has the new event and how to use it.
1. `npm i`
1. `npm t`
* none
* roll a new minor release
* migrate tests to use real data (todo in the codebase)
none
new code is covered, albeit not quite unit level, not quite integration level, but tests with this pattern should be easier to maintain.
> Enable 'referral' event for Messenger Code scans

- .eslintrc.js
- docs/Makefile
- docs/requirements.txt
- src/app.js
- test/app.spec.js
Messenger's docs say:
> As of the release of Messenger Platform v2.2, we are requesting developers to include the messaging_type property in all message sends.
> Beginning May 7, 2018, this property will be required for all message sends. After this date, message sends that do not include messaging_type will return an error and not be delivered.
https://developers.facebook.com/docs/messenger-platform/send-messages#messaging_types
This adds that field to the api calls so projects built on this won't break.
closes #86 
Sphinx docs are updated.
1. `npm i`
2. `npm t`
In your docs Python environment...
1. `cd docs && pip install requirements.txt`
2. `cd docs && make watch`
3. view api docs http://localhost:8000/api.html
I also did a `npm link …
> Add messaging_type for future compatibility

- .gitignore
- package-lock.json
- package.json
- test/app.spec.js
- test/conversationLogger.spec.js
- test/responses.spec.js
* Update to `sinon-5.x` to use new sandbox structure
* Seemed like a good time to `npm check` and update other dependencies
* Update coverage tool to `nyc` (istanbul command line interface)
No `README` changes. No interface changes to document.
`rm -rf node_modules coverage`
`npm i`
`npm t`
Optionally: `npm link` the update and test against a bot using the SDK as a dependency. This is not required as there are no major updates in the non-dev dependencies.
None identified.
Cut a new release in the near future.
None identified.
Unchanged!
> Update dependencies and coverage tool
